export const blocktowinContractAddress = 'HgDCYQefJ2eWbi4MKXLhuNTVAYzVyD6pxrWnk79Zqs57'

export const temporaryCompetitions = [
  {
    name: 'Competition 1',
    description: 'This is a competition',
    id: '1',
    tickets: 100,
    ticketCost: 1,
    ticketsSold: 50,
    startDate: new Date(),
    endDate: new Date(),
    poolPrize: 1000,
  },
  {
    name: 'Competition 2',
    description: 'This is a competition',
    id: '2',
    tickets: 100,
    ticketCost: 1,
    ticketsSold: 5,
    startDate: new Date(),
    endDate: new Date(),
    poolPrize: 250,
  },
  {
    name: 'Competition 3',
    description: 'This is a competition',
    id: '3',
    tickets: 100,
    ticketCost: 1,
    ticketsSold: 75,
    startDate: new Date(),
    endDate: new Date(),
    poolPrize: 500,
  },
  {
    name: 'Competition 4',
    description: 'This is a competition',
    id: '4',
    tickets: 100,
    ticketCost: 1,
    ticketsSold: 10,
    startDate: new Date(),
    endDate: new Date(),
    poolPrize: 100,
    isFinished: false,
  },
]
